const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.meetings = require("./MeetingModel.js")(mongoose);
db.rooms = require("./RoomModel.js")(mongoose);
module.exports = db;